import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { HeaderPublic } from "@/components/public/header_public";
import FooterPublic  from "@/components/public/footer_public";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="min-h-screen bg-[#f3f3f3] text-[#434343]"
        >
          <HeaderPublic />
            {children}
          <FooterPublic />
        </div>
      </body>
    </html>
  );
}
